mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'garethr/docker'
mod 'biemond-wls', '1.4.0'
mod 'biemond-orawls', '2.0.16'
mod 'biemond-orautils', '0.5.3'
